### ISSUE TITLE
ack stream:error

### ISSUE THREAD

**Issue by josemonino** [mgp25/Chat-API#1852]
Make sure these boxes are checked before submitting your issue -- thank you!

- [ x] You are using PHP > 5.6
- [ x] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [ x] You have checked if someone has already asked the same issue you have.
- [ x] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [ x] Is not a programming question.
- [ x] You are using latest Chat API code.

### Error
I'm working with ChatAPI perfectly at the moment, but somtimes I get this error

```xml
2016-04-19 23:38:32  [info] rx  <notification from="xxxxxxxxxxx@s.whatsapp.net" type="status" id="2253880928" notify="Wilder Garavito" t="1461109138">
rx    <set>e29b88</set>
rx  </notification>
2016-04-19 23:38:32  [info] tx  <ack to="xxxxxxxxxxx@s.whatsapp.net" class="notification" id="2253880928" type="status"></ack>
2016-04-19 23:42:09  [info] rx  <notification from="xxxxxxxxxxx@s.whatsapp.net" type="picture" id="745526107" notify="Wilder Garavito" t="1461109354">
rx    <set jid="xxxxxxxxxxx@s.whatsapp.net" id="1461109354"></set>
rx  </notification>
2016-04-19 23:42:09  [info] tx  <ack to="xxxxxxxxxxx@s.whatsapp.net" class="notification" id="745526107" type="picture"></ack>
2016-04-19 23:41:07  [info] rx  <notification from="xxxxxxxxxxx@s.whatsapp.net" type="picture" id="2676718661" notify="Wilder Garavito" t="1461109293">
rx    <set jid="xxxxxxxxxxx@s.whatsapp.net" id="1461109293"></set>
rx  </notification>
2016-04-19 23:41:07  [info] tx  <ack to="xxxxxxxxxxx@s.whatsapp.net" class="notification" id="2676718661" type="picture"></ack>
2016-04-19 23:41:09  [info] rx  <presence from="xxxxxxxxxxx@s.whatsapp.net"></presence>
2016-04-19 23:42:02  [info] rx  <presence from="xxxxxxxxxxx@s.whatsapp.net" type="unavailable" last="deny"></presence>
2016-04-19 23:43:11  [info] rx  <stream:error>
rx    <ack id="745526107"></ack>
rx  </stream:error>
```

I think I'm missing something when I get a notification but I don't know what to do. 

Thanks!

**Comment by mgp25** [comment]
@josemonino are you using latest Chat API code? If not, please download and retry again, because it seems outdated.

That occurs when you are not sending ack properly to a notificacion node

Regards

**Comment by josemonino** [comment]
I'm sure I'm using the latest Chat API code. Everyday i'm checking just in case you released the new one WA2.0 protocol :D

**Comment by anativ** [comment]
Had the same issue #1791 fixed by adding 1 line of code

**Comment by josemonino** [comment]
I did what @anativ said and at the moment no problems, but checking the code, that change shouldn't solve the notifications ack...in fact, it's related to "messages". 

I have to say that before the change, my ChatAPI used to do ack notifications perfectly exept some rare cases like that one I showed you. 

Crossing my fingers...

**Comment by jonathan-r** [comment]
+1 for the @anativ line of code !
Fixed my `stream:error` issue too.

**Comment by Creapix89** [comment]
@mgp25 I also had the same problem, this time was not to receive a message, but to send the message. It is the first time that happens to me. I share my debug.
regards

```

tx  <stream:features></stream:features>

tx  <auth user="5215531125251" mechanism="WAUTH-2">0091798835323135353331313235323531d93f547a2df4cd308ffa7bba51d4bf933baf5d7731343631343235323831</auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>c88e0e489f89fd4297fe3d73d3ff3a5d0f37ab13</challenge>

tx <response>b957e14a47ecd5b54c85c913e7780b45e9795e19d33733072bb9a61edcbc8dbcf3db1ee64fdf3d35f4574a8b1dd7233ddebddec73a3e900d920f394e24fd1d9e66acda2da11b22eb30357e0a69d611</response>

rx  <success t="1461425281" props="5" kind="free" status="active" creation="1446854314" expiration="4444444444">a2c62b8d1865bab2a56042e05e6428cee701798d</success>

tx  <presence name="Casa Saastun" type="available"></presence>

tx  <iq id="01" xmlns="jabber:iq:privacy" type="get">
tx    <query>
tx      <list name="default"></list>
tx    </query>
tx  </iq>

tx  <iq id="02" xmlns="urn:xmpp:whatsapp:push" type="get" to="s.whatsapp.net">
tx    <config></config>
tx  </iq>

tx  <iq id="03" xmlns="w:p" type="get" to="s.whatsapp.net">
tx    <ping></ping>
tx  </iq>

tx  <iq id="04" xmlns="urn:xmpp:whatsapp:sync" type="get">
tx    <sync mode="delta" context="interactive" sid="sync_sid_full_599d453e-4008-446a-9e40-05788c8df73d" index="0" last="true">
tx      <user>+5217225122465</user>
tx      <user>+5215528045769</user>
tx      <user>+5214423229003</user>
tx      <user>+5215530706832</user>
tx      <user>+5215527026306</user>
tx      <user>+5215537279163</user>
tx      <user>+5212741112653</user>
tx      <user>+5215514425973</user>
tx      <user>+5217771636443</user>
tx      <user>+5215531125251</user>
tx      <user>+5217716831532</user>
tx      <user>+5215549409215</user>
tx      <user>+5215534155621</user>
tx      <user>+5215544661217</user>
tx      <user>+5215554190115</user>
tx      <user>+5214422810399</user>
tx      <user>+5215543484278</user>
tx      <user>+5219933091373</user>
tx      <user>+5215548662625</user>
tx      <user>+5215551893564</user>
tx      <user>+5215537632182</user>
tx      <user>+5215528965419</user>
tx      <user>+5217757526611</user>
tx      <user>+5215514744470</user>
tx      <user>+5213107872370</user>
tx      <user>+5217771333746</user>
tx      <user>+5214731037179</user>
tx      <user>+5218110343394</user>
tx      <user>+5215534965429</user>
tx      <user>+5215566762970</user>
tx      <user>+5215515364084</user>
tx      <user>+5219981040753</user>
tx      <user>+5215555062353</user>
tx      <user>+5214422729712</user>
tx      <user>+5215513846494</user>
tx      <user>+5215519264556</user>
tx      <user>+5215560974090</user>
tx      <user>+5215525846152</user>
tx      <user>+5215510788017</user>
tx      <user>+5215543482078</user>
tx      <user>+5215567915420</user>
tx      <user>+4423567440</user>
tx      <user>+5215514816115</user>
tx      <user>+5215554564522</user>
tx      <user>+5215530122169</user>
tx      <user>+5215539996206</user>
tx      <user>+5216241579480</user>
tx      <user>+5215536419402</user>
tx      <user>+5215537348136</user>
tx      <user>+5215530706832</user>
tx    </sync>
tx  </iq>

rx  <presence from="5215531125251@s.whatsapp.net"></presence>

rx  <ib from="s.whatsapp.net">
rx    <offline count="0"></offline>
rx  </ib>

rx  <iq from="s.whatsapp.net" type="result" id="03" t="1461425281"></iq>

rx  <presence from="5212741112653@s.whatsapp.net" type="unavailable" last="deny"></presence>

rx  <iq from="5215531125251@s.whatsapp.net" type="error" id="1">
rx    <error code="404" text="item-not-found"></error>
rx  </iq>

rx  <presence from="5214422729712@s.whatsapp.net" type="unavailable" last="1461425132"></presence>

rx  <presence from="5215528965419@s.whatsapp.net" type="unavailable" last="1461424435"></presence>

rx  <iq from="s.whatsapp.net" type="result" id="02">
rx    <config platform="gcm" id="NfIZp_4qXGZ:APA91b8UkILZfGGwUIyfzAvGOPvoe4fIuyM5iT4WeOHThNuJjUPtT7qNPgkCFkeCHo7YFm_LEgee-ZJlSX3zwo7C8_AxbKyGqA2_iKofh9kqcNX_j_5ezgVqaG96lcgDgS6k6tNwSTcm"></config>
rx  </iq>

rx  <iq from="5215531125251@s.whatsapp.net" type="result" id="04">
rx    <sync index="0" sid="sync_sid_full_599d453e-4008-446a-9e40-05788c8df73d" last="true" version="1461276120286040">
rx      <in>
rx        <user jid="5219981040753@s.whatsapp.net">+5219981040753</user>
rx        <user jid="5219933091373@s.whatsapp.net">+5219933091373</user>
rx        <user jid="5218110343394@s.whatsapp.net">+5218110343394</user>
rx        <user jid="5217771636443@s.whatsapp.net">+5217771636443</user>
rx        <user jid="5217771333746@s.whatsapp.net">+5217771333746</user>
rx        <user jid="5217757526611@s.whatsapp.net">+5217757526611</user>
rx        <user jid="5217716831532@s.whatsapp.net">+5217716831532</user>
rx        <user jid="5217225122465@s.whatsapp.net">+5217225122465</user>
rx        <user jid="5216241579480@s.whatsapp.net">+5216241579480</user>
rx        <user jid="5215567915420@s.whatsapp.net">+5215567915420</user>
rx        <user jid="5215566762970@s.whatsapp.net">+5215566762970</user>
rx        <user jid="5215560974090@s.whatsapp.net">+5215560974090</user>
rx        <user jid="5215555062353@s.whatsapp.net">+5215555062353</user>
rx        <user jid="5215554564522@s.whatsapp.net">+5215554564522</user>
rx        <user jid="5215554190115@s.whatsapp.net">+5215554190115</user>
rx        <user jid="5215551893564@s.whatsapp.net">+5215551893564</user>
rx        <user jid="5215549409215@s.whatsapp.net">+5215549409215</user>
rx        <user jid="5215548662625@s.whatsapp.net">+5215548662625</user>
rx        <user jid="5215544661217@s.whatsapp.net">+5215544661217</user>
rx        <user jid="5215543484278@s.whatsapp.net">+5215543484278</user>
rx        <user jid="5215543482078@s.whatsapp.net">+5215543482078</user>
rx        <user jid="5215539996206@s.whatsapp.net">+5215539996206</user>
rx        <user jid="5215537632182@s.whatsapp.net">+5215537632182</user>
rx        <user jid="5215537348136@s.whatsapp.net">+5215537348136</user>
rx        <user jid="5215537279163@s.whatsapp.net">+5215537279163</user>
rx        <user jid="5215536419402@s.whatsapp.net">+5215536419402</user>
rx        <user jid="5215534965429@s.whatsapp.net">+5215534965429</user>
rx        <user jid="5215534155621@s.whatsapp.net">+5215534155621</user>
rx        <user jid="5215531125251@s.whatsapp.net">+5215531125251</user>
rx        <user jid="5215530706832@s.whatsapp.net">+5215530706832</user>
rx        <user jid="5215528965419@s.whatsapp.net">+5215528965419</user>
rx        <user jid="5215528045769@s.whatsapp.net">+5215528045769</user>
rx        <user jid="5215527026306@s.whatsapp.net">+5215527026306</user>
rx        <user jid="5215525846152@s.whatsapp.net">+5215525846152</user>
rx        <user jid="5215519264556@s.whatsapp.net">+5215519264556</user>
rx        <user jid="5215515364084@s.whatsapp.net">+5215515364084</user>
rx        <user jid="5215514816115@s.whatsapp.net">+5215514816115</user>
rx        <user jid="5215514744470@s.whatsapp.net">+5215514744470</user>
rx        <user jid="5215514425973@s.whatsapp.net">+5215514425973</user>
rx        <user jid="5215513846494@s.whatsapp.net">+5215513846494</user>
rx        <user jid="5215510788017@s.whatsapp.net">+5215510788017</user>
rx        <user jid="5214731037179@s.whatsapp.net">+5214731037179</user>
rx        <user jid="5214423229003@s.whatsapp.net">+5214423229003</user>
rx        <user jid="5214422810399@s.whatsapp.net">+5214422810399</user>
rx        <user jid="5214422729712@s.whatsapp.net">+5214422729712</user>
rx        <user jid="5212741112653@s.whatsapp.net">+5212741112653</user>
rx      </in>
rx      <out>
rx        <user jid="5215530122169@s.whatsapp.net">+5215530122169</user>
rx        <user jid="5213107872370@s.whatsapp.net">+5213107872370</user>
rx        <user jid="4423567440@s.whatsapp.net">+4423567440</user>
rx      </out>
rx    </sync>
rx  </iq>

tx  <presence type="subscribe" to="5219981040753@s.whatsapp.net"></presence>

tx  <presence type="subscribe" to="5219933091373@s.whatsapp.net"></presence>

tx  <presence type="subscribe" to="5218110343394@s.whatsapp.net"></presence>

tx  <presence type="subscribe" to="5217771636443@s.whatsapp.net"></presence>

tx  <presence type="subscribe" to="5217771333746@s.whatsapp.net"></presence>

tx  <presence type="subscribe" to="5217757526611@s.whatsapp.net"></presence>

tx  <presence type="subscribe" to="5217716831532@s.whatsapp.net"></presence>

tx  <presence type="subscribe" to="5217225122465@s.whatsapp.net"></presence>

tx  <presence type="subscribe" to="5216241579480@s.whatsapp.net"></presence>

tx  <presence type="subscribe" to="5215567915420@s.whatsapp.net"></presence>

tx  <presence type="subscribe" to="5215566762970@s.whatsapp.net"></presence>

tx  <presence type="subscribe" to="5215560974090@s.whatsapp.net"></presence>

tx  <presence type="subscribe" to="5215555062353@s.whatsapp.net"></presence>

tx  <presence type="subscribe" to="5215554564522@s.whatsapp.net"></presence>

tx  <presence type="subscribe" to="5215554190115@s.whatsapp.net"></presence>

tx  <presence type="subscribe" to="5215551893564@s.whatsapp.net"></presence>

tx  <presence type="subscribe" to="5215549409215@s.whatsapp.net"></presence>

tx  <presence type="subscribe" to="5215548662625@s.whatsapp.net"></presence>

tx  <presence type="subscribe" to="5215544661217@s.whatsapp.net"></presence>

tx  <presence type="subscribe" to="5215543484278@s.whatsapp.net"></presence>

tx  <presence type="subscribe" to="5215543482078@s.whatsapp.net"></presence>

tx  <presence type="subscribe" to="5215539996206@s.whatsapp.net"></presence>

tx  <presence type="subscribe" to="5215537632182@s.whatsapp.net"></presence>

tx  <presence type="subscribe" to="5215537348136@s.whatsapp.net"></presence>

tx  <presence type="subscribe" to="5215537279163@s.whatsapp.net"></presence>

tx  <presence type="subscribe" to="5215536419402@s.whatsapp.net"></presence>

tx  <presence type="subscribe" to="5215534965429@s.whatsapp.net"></presence>

tx  <presence type="subscribe" to="5215534155621@s.whatsapp.net"></presence>

tx  <presence type="subscribe" to="5215531125251@s.whatsapp.net"></presence>

tx  <presence type="subscribe" to="5215530706832@s.whatsapp.net"></presence>

tx  <presence type="subscribe" to="5215528965419@s.whatsapp.net"></presence>

tx  <presence type="subscribe" to="5215528045769@s.whatsapp.net"></presence>

tx  <presence type="subscribe" to="5215527026306@s.whatsapp.net"></presence>

tx  <presence type="subscribe" to="5215525846152@s.whatsapp.net"></presence>

tx  <presence type="subscribe" to="5215519264556@s.whatsapp.net"></presence>

tx  <presence type="subscribe" to="5215515364084@s.whatsapp.net"></presence>

tx  <presence type="subscribe" to="5215514816115@s.whatsapp.net"></presence>

tx  <presence type="subscribe" to="5215514744470@s.whatsapp.net"></presence>

tx  <presence type="subscribe" to="5215514425973@s.whatsapp.net"></presence>

tx  <presence type="subscribe" to="5215513846494@s.whatsapp.net"></presence>

tx  <presence type="subscribe" to="5215510788017@s.whatsapp.net"></presence>

tx  <presence type="subscribe" to="5214731037179@s.whatsapp.net"></presence>

tx  <presence type="subscribe" to="5214423229003@s.whatsapp.net"></presence>

tx  <presence type="subscribe" to="5214422810399@s.whatsapp.net"></presence>

tx  <presence type="subscribe" to="5214422729712@s.whatsapp.net"></presence>

tx  <presence type="subscribe" to="5212741112653@s.whatsapp.net"></presence>

tx  <iq id="05" xmlns="w:p" type="get" to="s.whatsapp.net">
tx    <ping></ping>
tx  </iq>

tx  <presence type="subscribe" to="5215537348136@s.whatsapp.net"></presence>

tx  <chatstate to="5215537348136@s.whatsapp.net">
tx    <composing></composing>
tx  </chatstate>

tx  <chatstate to="5215537348136@s.whatsapp.net">
tx    <paused></paused>
tx  </chatstate>

tx  <message to="5215537348136@s.whatsapp.net" type="text" id="6419d46605ee98343ab85b" t="1461425283" notify="Casa Saastun">
tx    <enc v="1" type="pkmsg">3328e4aab5840a08573005122105582224f643159a6d356271cb63a087cd421e844ab9ef298b236935db5fe08c7f1a2105ada55fce5b9d6719a48dedcaca1b33d9d89864371c1ba8c8ff8096395ab3c95f2260330a210540449aaff9b0f992a04978752b71bf690ca4c809819d1eb0def8929543e71a27105f2230749b58b824e5838c0b655c7795ece83193ad9be071bedff51e27ec027171fa81ffcf7aa6646529806fcc3c9efb1d19cb18e73f5bb13d0d33</enc>
tx  </message>

tx  <iq id="06" xmlns="w:p" type="get" to="s.whatsapp.net">
tx    <ping></ping>
tx  </iq>

tx  <presence type="subscribe" to="5215530706832@s.whatsapp.net"></presence>

tx  <chatstate to="5215530706832@s.whatsapp.net">
tx    <composing></composing>
tx  </chatstate>

tx  <chatstate to="5215530706832@s.whatsapp.net">
tx    <paused></paused>
tx  </chatstate>

tx  <message to="5215530706832@s.whatsapp.net" type="text" id="6419d46605ee98343ab85c" t="1461425284" notify="Casa Saastun">
tx    <enc v="1" type="msg">330a2105aec3e1db1fadfdd84067eb3fcf128ad60aa4fcfbab4dfd8391c07fe19bdabb3d1003180022305cfcc6822df0519822285872b6040afa4b8551f5852688d575f1daf9584b8f912fc05f918e836747772cbedeb91ed10ca6b07e948ee65046</enc>
tx  </message>

tx  <iq id="07" xmlns="w:p" type="get" to="s.whatsapp.net">
tx    <ping></ping>
tx  </iq>

rx  <presence from="5215554564522@s.whatsapp.net" type="unavailable" last="1461418607"></presence>

rx  <presence from="5219933091373@s.whatsapp.net" type="unavailable" last="1461422119"></presence>

rx  <presence from="5215567915420@s.whatsapp.net"></presence>

rx  <presence from="5215560974090@s.whatsapp.net" type="unavailable" last="1461425139"></presence>

rx  <presence from="5217716831532@s.whatsapp.net" type="unavailable" last="1461424279"></presence>

rx  <presence from="5217757526611@s.whatsapp.net" type="unavailable" last="1461425026"></presence>

rx  <presence from="5219981040753@s.whatsapp.net" type="unavailable" last="1461422166"></presence>

rx  <presence from="5219933091373@s.whatsapp.net" type="unavailable" last="1461422119"></presence>

rx  <presence from="5218110343394@s.whatsapp.net" type="unavailable" last="1461419319"></presence>

rx  <presence from="5217771636443@s.whatsapp.net" type="unavailable" last="1461388592"></presence>

rx  <presence from="5217771333746@s.whatsapp.net" type="unavailable" last="1461366752"></presence>

rx  <presence from="5217757526611@s.whatsapp.net" type="unavailable" last="1461425026"></presence>

rx  <presence from="5217225122465@s.whatsapp.net" type="unavailable" last="1461423730"></presence>

rx  <presence from="5215567915420@s.whatsapp.net"></presence>

rx  <presence from="5215566762970@s.whatsapp.net" type="unavailable" last="1461424311"></presence>

rx  <presence from="5216241579480@s.whatsapp.net" type="unavailable" last="1461377926"></presence>

rx  <presence from="5217716831532@s.whatsapp.net" type="unavailable" last="1461424279"></presence>

rx  <presence from="5215554564522@s.whatsapp.net" type="unavailable" last="1461418607"></presence>

rx  <presence from="5215555062353@s.whatsapp.net" type="unavailable" last="1461389272"></presence>

rx  <presence from="5215560974090@s.whatsapp.net" type="unavailable" last="1461425139"></presence>

rx  <presence from="5215554190115@s.whatsapp.net" type="unavailable" last="1461381527"></presence>

rx  <presence from="5215551893564@s.whatsapp.net" type="unavailable" last="1461376307"></presence>

rx  <presence from="5215548662625@s.whatsapp.net" type="unavailable" last="deny"></presence>

rx  <presence from="5215543482078@s.whatsapp.net" type="unavailable" last="1461393300"></presence>

rx  <presence from="5215544661217@s.whatsapp.net" type="unavailable" last="1461393510"></presence>

rx  <presence from="5215549409215@s.whatsapp.net" type="unavailable" last="1461423869"></presence>

rx  <presence from="5215537632182@s.whatsapp.net" type="unavailable" last="1461294541"></presence>

rx  <presence from="5215537348136@s.whatsapp.net" type="unavailable" last="deny"></presence>

rx  <presence from="5215543484278@s.whatsapp.net" type="unavailable" last="1461381520"></presence>

rx  <presence from="5215539996206@s.whatsapp.net" type="unavailable" last="1461420571"></presence>

rx  <presence from="5215537279163@s.whatsapp.net" type="unavailable" last="1460382029"></presence>

rx  <presence from="5215536419402@s.whatsapp.net" type="unavailable" last="1461419709"></presence>

rx  <presence from="5215534965429@s.whatsapp.net" type="unavailable" last="1461423937"></presence>

rx  <presence from="5215531125251@s.whatsapp.net"></presence>

rx  <presence from="5215534155621@s.whatsapp.net" type="unavailable" last="1461422410"></presence>

rx  <presence from="5215530706832@s.whatsapp.net" type="unavailable" last="deny"></presence>

rx  <presence from="5215527026306@s.whatsapp.net" type="unavailable" last="deny"></presence>

rx  <presence from="5215525846152@s.whatsapp.net" type="unavailable" last="1461370473"></presence>

rx  <presence from="5215519264556@s.whatsapp.net" type="unavailable" last="1461423469"></presence>

rx  <presence from="5215531125251@s.whatsapp.net"></presence>

rx  <presence from="5215528965419@s.whatsapp.net" type="unavailable" last="1461424435"></presence>

rx  <presence from="5215528045769@s.whatsapp.net" type="unavailable" last="1461419388"></presence>

rx  <presence from="5215515364084@s.whatsapp.net" type="unavailable" last="1461409838"></presence>

rx  <presence from="5215514816115@s.whatsapp.net" type="unavailable" last="deny"></presence>

rx  <presence from="5215514744470@s.whatsapp.net" type="unavailable" last="1461375275"></presence>

rx  <presence from="5215513846494@s.whatsapp.net" type="unavailable" last="1461423977"></presence>

rx  <presence from="5215510788017@s.whatsapp.net" type="unavailable" last="1461379691"></presence>

rx  <presence from="5214731037179@s.whatsapp.net" type="unavailable" last="1461300304"></presence>

rx  <presence from="5215514425973@s.whatsapp.net" type="unavailable" last="1461416580"></presence>

rx  <iq from="s.whatsapp.net" type="result" id="05" t="1461425282"></iq>

rx  <presence from="5214422810399@s.whatsapp.net" type="unavailable" last="1461369878"></presence>

rx  <presence from="5212741112653@s.whatsapp.net" type="unavailable" last="deny"></presence>

rx  <presence from="5214422729712@s.whatsapp.net" type="unavailable" last="1461425132"></presence>

rx  <presence from="5214423229003@s.whatsapp.net" type="unavailable" last="1461385075"></presence>

rx  <presence from="5215537348136@s.whatsapp.net" type="unavailable" last="deny"></presence>

rx  <ack from="5215537348136@s.whatsapp.net" class="message" id="6419d46605ee98343ab85b" t="1461425283"></ack>

rx  <iq from="s.whatsapp.net" type="result" id="06" t="1461425283"></iq>

rx  <presence from="5215530706832@s.whatsapp.net" type="unavailable" last="deny"></presence>

rx  <ack from="5215530706832@s.whatsapp.net" class="message" id="6419d46605ee98343ab85c" t="1461425284"></ack>

rx  <iq from="s.whatsapp.net" type="result" id="07" t="1461425284"></iq>

tx  <iq id="08" xmlns="w:p" type="get" to="s.whatsapp.net">
tx    <ping></ping>
tx  </iq>

rx  <iq from="s.whatsapp.net" type="result" id="08" t="1461425286"></iq>

rx  <receipt from="5215537348136@s.whatsapp.net" id="6419d46605ee98343ab85b" t="1461425287"></receipt>

tx  <ack to="5215537348136@s.whatsapp.net" class="receipt" id="6419d46605ee98343ab85b"></ack>

rx  <receipt from="5215530706832@s.whatsapp.net" id="6419d46605ee98343ab85c" t="1461425290"></receipt>

tx  <ack to="5215530706832@s.whatsapp.net" class="receipt" id="6419d46605ee98343ab85c"></ack>

rx  <presence from="5215567915420@s.whatsapp.net" type="unavailable" last="1461425296"></presence>

rx  <stream:error>
rx    <ack id="6419d46605ee98343ab85b"></ack>
rx  </stream:error>


Fatal error: Uncaught exception 'ConnectionException' with message 'Connection Closed!' in /whatsapp/src/whatsprot.class.php:299
Stack trace:
#0 server.php(485): WhatsProt->pollMessage()
#1 {main}
 thrown in whatsapp/src/whatsprot.class.php on line 299
```

**Comment by josemonino** [comment]
```xml
2016-04-30 17:38:54  [info] tx  <presence type="subscribe" to="xxxxxxxxxx37@s.whatsapp.net"></presence>
2016-04-30 19:50:25  [info] rx  <presence from="xxxxxxxxxx37@s.whatsapp.net"></presence>
2016-04-30 19:55:50  [info] rx  <presence from="xxxxxxxxxx37@s.whatsapp.net" type="unavailable" last="1462045672"></presence>
2016-04-30 19:55:52  [info] rx  <notification from="xxxxxxxxxx37@s.whatsapp.net" type="picture" id="627565397" notify="milena chavez" t="1462045746">
rx    <set jid="xxxxxxxxxx37@s.whatsapp.net" id="1462045745"></set>
rx  </notification>
2016-04-30 19:55:52  [info] tx  <ack to="xxxxxxxxxx37@s.whatsapp.net" class="notification" id="627565397" type="picture"></ack>
2016-04-30 19:55:52  [info] rx  <presence from="xxxxxxxxxx37@s.whatsapp.net"></presence>
2016-04-30 20:05:59  [info] rx  <notification from="xxxxxxxxxx37@s.whatsapp.net" type="status" id="4221312673" notify="milena chavez" t="1462045775">
rx    <set>54656d70657261747572652e2e2e2e7365616e207061756c20f09f8eb6</set>
rx  </notification>
2016-04-30 20:05:59  [info] tx  <ack to="xxxxxxxxxx37@s.whatsapp.net" class="notification" id="4221312673" type="status"></ack>
2016-04-30 20:06:01  [info] rx  <notification from="xxxxxxxxxx37@s.whatsapp.net" type="status" id="2477853322" notify="milena chavez" t="1462045781">
rx    <set>4d616c6120636f6e64756374612e2e2e2e616c657869732079206669646f206674206672616e636f20656c20676f72696c6120f09f8eb6</set>
rx  </notification>

2016-04-30 20:06:01  [info] tx  <ack to="xxxxxxxxxx37@s.whatsapp.net" class="notification" id="2477853322" type="status"></ack>
2016-04-30 20:06:02  [info] rx  <presence from="xxxxxxxxxx37@s.whatsapp.net" type="unavailable" last="1462045790"></presence>

2016-04-30 20:06:03  [info] rx  <stream:error>
rx    <ack id="627565397"></ack>
rx  </stream:error>

```

Again same error. My code is modified with what @anativ said in #1791. But at the beginning of this thread it wasn't and I got the same error...

We are missing something with notifications...

**Comment by mgp25** [comment]
@josemonino did it happen again to you?

**Comment by aitriago** [comment]
Hi @mgp25 
Since today, I'm facing this problem with a client that I had working completely successfully from about 6 weeks ago (Never a  SPAM service, just an interactive service for consulting balances).
Here I attach the data flow, to see if you can see anything, I've just deleted the .db files, but still facing the same problem. I downloaded the latest version in order to see if there were some discrepancies, but nothing. 

The first time it fails, there was something like this:
`
rx  <chatstate from="573165319984@s.whatsapp.net">
rx    <paused></paused>
rx  </chatstate>

rx  <presence from="573176687809@s.whatsapp.net" type="unavailable" last="1462221067"></presence>

rx  <chatstate from="573165319984@s.whatsapp.net">
rx    <composing></composing>
rx  </chatstate>

rx  <chatstate from="573104209462@s.whatsapp.net">
rx    <paused></paused>
rx  </chatstate>

rx  <chatstate from="573104209462@s.whatsapp.net">
rx    <composing></composing>
rx  </chatstate>

rx  <message from="57XXXXXXX@s.whatsapp.net" type="text" id="8A919F09E5C534807FBB0E1415476F" t="1462221068" notify
="XXXX YYYY">
rx    <enc v="2" type="msg">330a2105787cc20cebce52567157150a44b6bb453f6ef790fa7e30bb9d4c9c0bf83cfd6d1000180022b001cf9
3bb398cbc76e166a935786f5e1fee6391740885d8bdbf8bfcb3fdf94685a2305919066b7fdf180058ddb763458c5ff0c30f6df29fdc37a7df0dae
6bbd37f171b05cd6fb86905878077255ab7278a5061819f1f6e5b69ff1a4e16bf837b6666f66c5232604b14ba34410a15cd02072bcc40a260884a
ea4f3716687c88039b918f56edd0d1b08bf2c3d33c82b8edfe70f436d56cc58a73dab31ce2ebba58eb8556e231173c29520eda1bdd6b766c4c4b3
609e553a09c690</enc>
rx  </message>

tx  <ack to="573104209462@s.whatsapp.net" class="message" id="8A919F09E5C534807FBB0E1415476F" t="1462221068"></ack>

-> Decrypted Message: Recarga XXXX YYYYY 1000 <--

tx  <receipt type="read" to="573104209462@s.whatsapp.net" id="8A919F09E5C534807FBB0E1415476F" t="1462221068"></receipt>
rx  <presence from="573102342962@s.whatsapp.net" type="unavailable" last="deny"></presence>

rx  <presence from="573YYYYYYY@s.whatsapp.net"></presence>

rx  <message from="573YYYYYYY@s.whatsapp.net" type="text" id="19B9CD69FC6ED93B18E7BF0691F916" t="1462221072" notify="Jaqueline">
rx    <enc v="2" type="msg">330a210549da08826f61275ab22146024ecf7887c0f09fb2aa5f64e139d8736550b81c5e10001800228001d07ab5545f91b28c3caff8eec52c56ab38980237f04552213d6a1c1037a64a1f2f3b9560a0e5d149ca9f275723e59973a9d8ec460d166af72986327dfb9598890056b044d14939d84363bf852471e27cd88639700757c9053426fa8d5a97d336f704c75a2c692c5a5fd9e0fad7de7c74daa8416a4bff930660aafba93dd9631ab226fb9546f379dc</enc>
rx  </message>

tx  <ack to="573165319984@s.whatsapp.net" class="message" id="19B9CD69FC6ED93B18E7BF0691F916" t="1462221072"></ack>

-> Decrypted Message: Recarga xxxxx yyyyy 10000

tx  <receipt type="read" to="573165319984@s.whatsapp.net" id="19B9CD69FC6ED93B18E7BF0691F916" t="1462221072"></receipt>

rx  <presence from="573176474823@s.whatsapp.net" type="unavailable" last="1462221078"></presence>

rx  <presence from="573102342962@s.whatsapp.net"></presence>


tx  <chatstate to="573XXXXXXX@s.whatsapp.net">
tx    <composing></composing>
tx  </chatstate>

tx  <message to="573XXXXXXX@s.whatsapp.net" type="text" id="629161b148931a8154ef5f" t="1462221106" notify="My Service">
tx    <enc v="2" type="msg">330a2105df34651a9d6e805907f1ba49375af51b22a124ab4fffb8f3cf046673baea2e121000180022607f955a08125f376799efc87d60e0ac5cdd99e52dfa800bea260ffc33d716290f715e399ec524fa6c5622b14c42730eb3a5f2aa4169a4d50091159b902e7dff21e00a3961ff96b7a3ba08bf3c064d93072a95cddae88caed040db6b5ffee799a26e40c830af08ea0f</enc>
tx  </message>

tx  <chatstate to="573165319984@s.whatsapp.net">
tx    <composing></composing>
tx  </chatstate>

tx  <message to="57XXXXXXX@s.whatsapp.net" type="text" id="629161b148931a8154ef60" t="1462221108" notify="My Service">
tx    <enc v="2" type="msg">330a2105a4297f26a02adc4b5670406aeb78d9c1576c4a030ec536d63ec984d9b9d45000100018002260e732a3b22fab73fa0c8bf309a7c046d24a5c6254f6fdffddd477c3d4b89d9b3532d98125ac0c9c38898ed4ed8043e3412cb77256221e932284a93b6025f1a94c8b6911d3639c790e6ccb8a1e0859eb79478938984083ed3619daeec139c449826d0da3d4bebc34ab</enc>
tx  </message>

rx  <chatstate from="57XXXXXXX@s.whatsapp.net">
rx    <paused></paused>
rx  </chatstate>

rx  <chatstate from="57XXXXXXX@s.whatsapp.net">
rx    <composing></composing>
rx  </chatstate>

rx  <chatstate from="57XXXXXXX@s.whatsapp.net">
rx    <paused></paused>
rx  </chatstate>

rx  <stream:error>
rx    <ack id="8A919F09E5C534807FBB0E1415476F"></ack>
rx  </stream:error>

Exception error! (Generally, connection failure!)
`

Now, everytime I login, I receive NO new messages (Just "Composing"):
`
...
tx  <iq id="0d" xmlns="encrypt" type="get" to="s.whatsapp.net">
tx    <key>
tx      <user jid="57mynumber@s.whatsapp.net"></user>
tx    </key>
tx  </iq>

rx  <iq from="573xxxxxxx@s.whatsapp.net" type="error" id="1">
rx    <error code="404" text="item-not-found"></error>
rx  </iq>

rx  <iq from="s.whatsapp.net" type="error" id="02">
rx    <error code="404" text="item-not-found"></error>
rx  </iq>

tx  <iq id="0e" type="set" xmlns="urn:xmpp:whatsapp:push" to="s.whatsapp.net">
tx    <config platform="gcm" id="KtfX1_z83HQ:APA91bJOTXoIaugcewII7gumkLoGAmy5Ul3kZgCz4DFUSAGMbkHVyfnRurCAy8CnkFE7nK_OG1S7-10SMuRx5lXNV_tmVFoxrtW_YBICitZLbat_e_oQnGQNTgV2MeGgUENesIy6jHaK"></config>
tx  </iq>

tx  <iq id="0f" to="573183349132@s.whatsapp.net" type="set" xmlns="w:profile:picture">
tx    <picture type="image"> 44304 byte data</picture>
tx    <picture type="preview"> 3535 byte data</picture>
tx  </iq>

tx  <iq to="s.whatsapp.net" type="set" id="10" xmlns="status">
tx    <status>Escriba 'AYUDA' para recibir la lista de comandos</status>
tx  </iq>
[] starting WS loop. Send /quit to close

`
<and after a while, something about 10 seconds>
`
rx <stream:error>
rx    <ack id="69709E744DF689052C7E615CC856DB"></ack>
rx  </stream:error>
`

Now, no messages are received and sent. Something wrong with the keys? I found a lot of:

-> Decrypted Message: Received message with old counter: 1 0 - /root/development/whatsAppApplications/downloads/git/C
hat-API/src/libaxolotl-php/SessionCipher.php - 238Message 3EB07E618D270683B4B2 could not be decrypted, sending retry.

Any help would be appreciated!

Regards.-

**Comment by josemonino** [comment]
Another trace doing the same...
```xml
2016-05-21 09:30:46 onConnectReceived [info] Number: xxxxxxxxx32 Socket: Resource id #106
2016-05-21 09:30:46  [info] tx  <stream:features></stream:features>
2016-05-21 09:30:46  [info] tx  <auth user="xxxxxxxxx32" mechanism="WAUTH-2">2aebbfe23332343630323031343830127adc47dcc0c23c5b0fb2f789063d2e7ae9ffa531343633383233303436</auth>
2016-05-21 09:30:46  [info] rx  <from s.whatsapp.net=""></from>
2016-05-21 09:30:46  [info] rx  <stream:features></stream:features>
2016-05-21 09:30:46  [info] rx  <challenge>44c0839eb85c69dc5074e75d20f2a5ad0db1b248</challenge>
2016-05-21 09:30:46  [info] tx  <response>4695f727dba1df52fe9955d61192d66363f611036d47bb71af1ee435cce1f236e647dd234a325511af38cb741aad28ce72027e8b4bd8788fd7a87dcf60d4cde112559f5bd6d6ed137bf7721791</response>
2016-05-21 09:30:46  [info] rx  <success t="1463815882" props="5" kind="free" status="active" creation="1461602263" expiration="4444444444">5623cea3bb4a45c59112fadbedcbf5693b0329e5</success>
2016-05-21 09:30:46  [info] tx  <presence name="Jose" type="available"></presence>
2016-05-21 09:30:46  [info] tx  <iq id="01" xmlns="jabber:iq:privacy" type="get">
tx    <query>
tx      <list name="default"></list>
tx    </query>
tx  </iq>
2016-05-21 09:30:46  [info] tx  <iq id="02" xmlns="urn:xmpp:whatsapp:push" type="get" to="s.whatsapp.net">
tx    <config></config>
tx  </iq>
2016-05-21 09:30:46  [info] tx  <iq id="03" xmlns="jabber:iq:privacy" type="get">
tx    <query>
tx      <list name="default"></list>
tx    </query>
tx  </iq>
2016-05-21 09:30:46  [info] tx  <iq id="04" xmlns="urn:xmpp:whatsapp:push" type="get" to="s.whatsapp.net">
tx    <config></config>
tx  </iq>
2016-05-21 09:30:46  [info] rx  <notification from="xxxxxxxxx84@s.whatsapp.net" type="contacts" id="3262753743" offline="1" t="1463781504">
rx    <update jid="xxxxxxxxx84@s.whatsapp.net"></update>
rx  </notification>
2016-05-21 09:30:46 onNumberWasUpdatedReceived [info] Number: xxxxxxxxx32 Jid: xxxxxxxxx84@s.whatsapp.net
2016-05-21 09:32:57  [info] tx  <ack to="xxxxxxxxx84@s.whatsapp.net" class="notification" id="3262753743" type="contacts"></ack>
2016-05-21 09:32:57  [info] rx  <notification from="xxxxxxxxx84@s.whatsapp.net" type="contacts" id="898381010" offline="0" t="1463781687">
rx    <update jid="xxxxxxxxx84@s.whatsapp.net"></update>
rx  </notification>
2016-05-21 09:32:57 onNumberWasUpdatedReceived [info] Number: xxxxxxxxx32 Jid: xxxxxxxxx84@s.whatsapp.net
2016-05-21 09:35:05  [info] tx  <ack to="xxxxxxxxx84@s.whatsapp.net" class="notification" id="898381010" type="contacts"></ack>
2016-05-21 09:35:05 onCloseReceived [info] Number: xxxxxxxxx32 Error: Connection closed!
2016-05-21 09:37:14  [info] rx  <notification from="xxxxxxxxx84@s.whatsapp.net" type="contacts" id="2602277339" offline="0" t="1463781732">
rx    <update jid="xxxxxxxxx84@s.whatsapp.net"></update>
rx  </notification>status
2016-05-21 09:37:14 onNumberWasUpdatedReceived [info] Number: xxxxxxxxx32 Jid: xxxxxxxxx84@s.whatsapp.net

```

Could it be related to the client's date? maybe the PC clock was not completly on time but 1-2 minutes earlier than UTC time.

**Comment by mgp25** [comment]
@josemonino i close this issue since i think is fixed in the next release, anyway, send me an email or contact with me to see what happens and try to find a solution here

Regards

**Comment by mgp25** [comment]
@josemonino i close this issue since i think its already fixed in the next rekease, anyway, contact with my if you face this issue again and ill try to help you fixing this at your side

Regards

**Comment by josemonino** [comment]
Perfect :). Thanks @mgp25
